In [2]:
import numpy as np
import time

In [6]:
#Vector Creation

# NumPy routines which allocate memory and fill arrays with value

a = np.zeros(4); print(f"np.zeros(4) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,)); print(f"np.zeros(4) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.zeros(4) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4) :  a = [0.17132636 0.77543313 0.62481525 0.25009673], a shape = (4,), a data type = float64


In [8]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument

a = np.arange(4.); print(f"np.zeros(4) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4); print(f"np.zeros(4) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :  a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.zeros(4) :  a = [0.54344463 0.4518922  0.27412354 0.18654962], a shape = (4,), a data type = float64


In [9]:
# NumPy routines which allocate memory and fill with user specified values

a = np.array([5,4,3,2]); print(f"np.zeros(4) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.zeros(4) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :  a = [5 4 3 2], a shape = (4,), a data type = int32
np.zeros(4) :  a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [15]:
#Operations on Vectors

a = np.arange(10)
print(a)

#Access an element

print(f"a[2].shape: {a[2].shape} a[2] = {a[2]}, Accesing an element returns a scalar")

#Access the last element

print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error

try:
    c = a[10]
except Exception as e:
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2] = 2, Accesing an element returns a scalar
a[-1] = 9
index 10 is out of bounds for axis 0 with size 10


In [21]:
#Slicing (start:stop:step)

a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1]; print("a[2:7:1] =", c)

#access 3 elements separated by two
c = a[2:7:2]; print("a[2:7:2]=", c)

#access all elements index 3 and above

c = a[3:]; print("a[3:] = ", c)


#access all elements below index 3

c = a[:3]; print("a[:3] = ", c)

#access all elements

c = a[:]; print("a[:]", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] = [2 3 4 5 6]
a[2:7:2]= [2 4 6]
a[3:] =  [3 4 5 6 7 8 9]
a[:3] =  [0 1 2]
a[:] [0 1 2 3 4 5 6 7 8 9]


In [25]:
#Single vector operations

a = np.array([1,2,3,4])
print(f"a: {a}")
#negate elements of a
b = -a
print(f"b = -a : {b}")


#Sum all elements of a, returns a scalar

b = np.sum(a)
print(f"np.sum(a) : {b}")

b = np.mean(a)
print(f"np.mean(a) : {b}")

b = a**2
print(f"a**2: {b}")

a: [1 2 3 4]
b = -a : [-1 -2 -3 -4]
np.sum(a) : 10
np.mean(a) : 2.5
a**2: [ 1  4  9 16]


In [28]:
#Vector Vector element-wise operations

a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])
print(f"Binary operations work element wise (if same size): {a + b}")

Binary operations work element wise (if same size): [0 0 6 8]


In [29]:
#Mismatched vectors

c = np.array([1,2])

try:
    d = a + c

except Exception as e:
    print(e)

operands could not be broadcast together with shapes (4,) (2,) 


In [30]:
#Scalaer Vector Operations

a = np.array([1,2,3,4])

#multiply a by a scalar

b = 5 * a
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


In [31]:
#Vector to Vector dot product (multiplies the values in two vectors element-wise and then sums the result).

def my_dot(a,b):
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [32]:
#Test 1-D

a = np.array([1,2,3,4])
b = np.array([-1, 4, 3, 2])

print(f"my_dot(a,b) = {my_dot(a,b)}")

my_dot(a,b) = 24


In [34]:
#Using numpy np.dot function

# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])

c = np.dot(a,b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")

NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


In [37]:
#Vectors vs Loops

np.random.seed(1)

a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time() #capture start time
c = np.dot(a,b)
toc = time.time()

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 12.0049 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 6567.0450 ms 


In [40]:
#Example

X = np.array([[1], [2], [3], [4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")



X[1] has shape (1,)
w has shape (1,)
c has shape ()


In [43]:
#Matrices

#Creation

a = np.zeros((1,5))
print(f"a shape = {a.shape}, a = {a}")


a = np.zeros((2,1))
print(f"a shape = {a.shape}, a = {a}")

a = np.zeros((1,1))
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.]]


In [45]:
# NumPy routines which allocate memory and fill with user specified values

a = np.array([[5], [4], [3]]); print(f"a shape = {a.shape}, np.array: a = {a}")

a = np.array([[5],  # One can also
              [4],  # separate values
              [3]]); #into separate rows
print(f"a shape = {a.shape}, np.array: a = {a}")

a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [52]:
#Operatioins on Matrices

a = np.arange(6).reshape(3,2)
print(f"a.shape: {a.shape}, \na = {a}")

#Access an element

print(f"\na[2,0].shape: {a[2,0].shape}, a[2,0] = {a[2,0]}, type(a[2,0]) = {type(a[2,0])} Accessing an element returns a scalar\n")

#Access a row

print(f"a[2].shape: {a[2].shape}, a[2] = {a[2]}, type(a[2]) = {type(a[2])}")

a.shape: (3, 2), 
a = [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape: (), a[2,0] = 4, type(a[2,0]) = <class 'numpy.int32'> Accessing an element returns a scalar

a[2].shape: (2,), a[2] = [4 5], type(a[2]) = <class 'numpy.ndarray'>


In [60]:
#Slicing (start:stop:step).

#Vector 2-D slicing operaations

a = np.arange(20). reshape(-1, 10)

print(f"a = \n {a}")

#Access 5 consecutive elements (start:stop:step):

print("a[0, 2:7:1] = ", a[0,2:7:1], "a[0,2:7:1].shape = ", a[0,2:7:1].shape, "a 1-D array")

#Access 5 consecutive elements in two rows (start:stop:step):

print("a[:, 2:7:1] = \n", a[:,2:7:1], "a[:,2:7:1].shape = ", a[:,2:7:1].shape, "a 1-D array")

#Access all elements

print("a[:,:]}", a[:,:], ", a[:,:].shape = ", a[:,:].shape)

#Access all elements in one row

print("a[1,:]}", a[1,:], ", a[1,:].shape = ", a[1,:].shape, "a 1-D array")

#same as

print("a[1]}", a[1], ", a[1].shape = ", a[1].shape, "a 1-D array")


a = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] a[0,2:7:1].shape =  (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] a[:,2:7:1].shape =  (2, 5) a 1-D array
a[:,:]} [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] , a[:,:].shape =  (2, 10)
a[1,:]} [10 11 12 13 14 15 16 17 18 19] , a[1,:].shape =  (10,) a 1-D array
a[1]} [10 11 12 13 14 15 16 17 18 19] , a[1].shape =  (10,) a 1-D array
